apiVersion: apps/v1
kind: Deployment
metadata:
  name: department-service
  annotations:
    appinsights.connstr: InstrumentationKey=ed9baecd-d00e-46fd-a584-baefb918ca65;IngestionEndpoint=https://japaneast-1.in.applicationinsights.azure.com/;LiveEndpoint=https://japaneast.livediagnostics.monitor.azure.com/
    appinsights.role: department-service
spec:
  selector:
    matchLabels:
      app: department-service
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: department-service
    spec:
      containers:
      - name: department-service
        image: nikawang.azurecr.io/spring/department-service:v11-noagent
        ports:
        - containerPort: 80
