apiVersion: apps/v1
kind: Deployment
metadata:
  name: organization-service
spec:
  selector:
    matchLabels:
      app: organization-service
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: organization-service
    spec:
      containers:
      - name: organization-service
        image: nikawang.azurecr.io/spring/organization-service:v11
        ports:
        - containerPort: 80






