apiVersion: apps/v1
kind: Deployment
metadata:
  name: department-service
spec:
  selector:
    matchLabels:
      app: department-service
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: department-service
    spec:
      containers:
      - name: department-service
        image: nikawang.azurecr.io/spring/department-service:v11
        ports:
        - containerPort: 80






